// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionDialog: typeof import('./../src/components/action/Dialog.vue')['default']
    Dialog: typeof import('./../src/components/action/Dialog.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NSpace: typeof import('naive-ui')['NSpace']
    Search: typeof import('./../src/components/Search.vue')['default']
    Table: typeof import('./../src/components/Table.vue')['default']
    Theme: typeof import('./../src/components/Theme.vue')['default']
  }
}
