// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    AStatistic: typeof import('@arco-design/web-vue')['Statistic']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    IconAdd: typeof import('@arco-design/web-vue/es/icon')['IconAdd']
    IconArrowRise: typeof import('@arco-design/web-vue/es/icon')['IconArrowRise']
    IconDelete: typeof import('@arco-design/web-vue/es/icon')['IconDelete']
    IconDragArrow: typeof import('@arco-design/web-vue/es/icon')['IconDragArrow']
    IconEdit: typeof import('@arco-design/web-vue/es/icon')['IconEdit']
    IconFile: typeof import('@arco-design/web-vue/es/icon')['IconFile']
    IconFolder: typeof import('@arco-design/web-vue/es/icon')['IconFolder']
    IconFolderAdd: typeof import('@arco-design/web-vue/es/icon')['IconFolderAdd']
    IconLaunch: typeof import('@arco-design/web-vue/es/icon')['IconLaunch']
    IconMobile: typeof import('@arco-design/web-vue/es/icon')['IconMobile']
    IconMoon: typeof import('@arco-design/web-vue/es/icon')['IconMoon']
    IconRefresh: typeof import('@arco-design/web-vue/es/icon')['IconRefresh']
    IconSun: typeof import('@arco-design/web-vue/es/icon')['IconSun']
    Table: typeof import('./../src/components/Table.vue')['default']
    Tabs: typeof import('./../src/components/Tabs.vue')['default']
    Theme: typeof import('./../src/components/theme.vue')['default']
    Zone: typeof import('./../src/components/Zone.vue')['default']
  }
}
